### ISSUE TITLE
using time slider on playback UI crashes mopidy

### ISSUE THREAD

**Issue by IanRogers-LShift** [palfrey/mopidy-jukebox#15]
```
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: Traceback (most recent call last):
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/mopidy/audio/actor.py", line 539, in _on_about_to_finish
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: self._about_to_finish_callback()
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 247, in _on_about_to_finish_callback
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: 'attr_path': ('playback', '_on_about_to_finish'),
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 435, in ask
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: return future.get(timeout=timeout)
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: compat.reraise(*self._data['exc_info'])
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: exec('raise tp, value, tb')
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: response = self._handle_receive(message)
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: return callee(*message['args'], **message['kwargs'])
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 258, in _on_about_to_finish
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: self._last_position = self._current_tl_track.track.length
Sep 27 10:18:00 mopidy-jukebox mopidy[20157]: AttributeError: 'NoneType' object has no attribute 'track'
```

**Comment by palfrey** [comment]
This might be a problem with upstream Mopidy (https://github.com/mopidy/mopidy)

**Comment by palfrey** [comment]
Or might require updating the frontend... (taken from https://github.com/pimusicbox/mopidy-musicbox-webclient but forked at https://github.com/palfrey/mopidy-musicbox-webclient)
